config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="base.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("hidden_pigeon.users.urls", namespace="users")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# SILKY
urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hidden_pigeon/users/urls.py
from django.urls import path

from hidden_pigeon.users.views import user_detail_view, user_redirect_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

projects/urls.py
from django.urls import path

from .views import expand_project_hx, my_projects_view

app_name = "projects"
urlpatterns = [
    path("", view=my_projects_view, name="list"),
    path("expanded_hx/<int:pk>", view=expand_project_hx, name="expanded_project"),
]

hidden_pigeon/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for HIDDEN PIGEON.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

projects/models.py
from django.db import models
from django.urls import reverse


class Project(models.Model):
    name = models.CharField(null=False, blank=False, max_length=500)
    creator = models.ForeignKey("users.User", on_delete=models.CASCADE)

    def get_absolute_url(self):
        """Get url for user's detail view.
        Returns:
            str: URL for project detail.

        """
        return reverse("projects:detail", kwargs={"pk": self.pk})

    def __str__(self):
        """Get str ref for model title

        Returns:
            str: self.name.

        """
        return f"{self.name} - {self.pk}"


class Scene(models.Model):
    name = models.CharField(null=False, blank=False, max_length=500)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)

    def get_absolute_url(self):
        """Get url for user's detail view.
        Returns:
            str: URL for project detail.

        """
        return reverse("projects:scene_detail", kwargs={"pk": self.pk})

    def __str__(self):
        """Get str ref for model title

        Returns:
            str: self.name.

        """
        return self.name

hidden_pigeon/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

hidden_pigeon/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import RedirectView

User = get_user_model()


def user_detail_view(request, username):

    this_user = User.objects.get(username=username)

    return render(request, "../templates/users/user_detail.html", {"object": this_user})


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import Project, Scene


@login_required
def my_projects_view(request):
    projects = Project.objects.filter(creator=request.user)
    return render(request, "projects.html", {"projects": projects})


def expand_project_hx(request, pk):

    project = Project.objects.get(id=pk)
    scenes = Scene.objects.filter(project_id=pk)

    return render(
        request,
        "partials/expanded_project.html",
        {"project": project, "scenes": scenes},
    )

hidden_pigeon/templates/base-nav.html
{% extends "base.html" %}
{% load static i18n %}
{% block navbar %}
    <nav style="background: white !important;" class="navbar navbar-expand-md navbar-light bg-light">
        <div style="background: white !important;" class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">HIDDEN PIGEON</a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'projects:list' %}">{% translate "MY PROJECTS" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
              </li>
              {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
{% endblock navbar %}

hidden_pigeon/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}HIDDEN PIGEON{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A site for storing and serving assets related to film production.">
    <meta name="author" content="lance knickerbocker">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="https://unpkg.com/htmx.org@1.7.0"></script>
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body style="font-family: 'Courier Prime', monospace; text-transform: uppercase;">

    <div class="mb-1">
      {% block navbar %}

      {% endblock navbar %}
    </div>

    <div class="container">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
      <div class="header" style="height:300px;">
      </div>
      <div class="row text-center">
        <h1>HIDDEN PIGEON</h1>
      </div>
      <div class="text-center">
        <a stye="color: black; decoration: none;" href="{% url 'account_login' %}">WOG IN</a> | WOG OUT
      </div>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
    <div style="height: 400px;"></div>
    <footer class="footer mt-auto py-3">
      <div class="container" style="min-height: 100%; margin-bottom: -50px;">
        <span class="text-muted">hidden pigeon 2022 - website by <a style="color: black;" href="https://www.freelancelance.com">freelance lance</a></span>
      </div>
    </footer>
  </body>
</html>

hidden_pigeon/templates/users/user_detail.html
{% extends "base-nav.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">
</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

hidden_pigeon/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

projects/templates/partials/expanded_project.html
<div id="project-{{project.pk}}">
    <h1><span hx-get="{% url 'projects:expanded_project' project.pk %}"
        hx-trigger="click"
        hx-target="#project-{{project.pk}}"
        hx-swap="outerHTML"
        >-</span>{{project.name}}</h1>
    {% for scene in scenes  %}
    <p>{{scene.name}}</p>
    {% endfor %}
</div>

projects/templates/projects.html
{% extends "base-nav.html" %}
{% load static %}

{% block title %}{{ request.username }}'s PROJECTS{% endblock %}

{% block content %}
<div>
    {% for project in projects  %}
    <div id="project-{{project.pk}}">
        <h1><span hx-get="{% url 'projects:expanded_project' project.pk %}"
            hx-trigger="click"
            hx-target="#project-{{project.pk}}"
            hx-swap="outerHTML"
            >+</span>{{project.name}}</h1>
    </div>
    {% endfor %}
</div>
{% endblock content %}